### ISSUE TITLE
有bug啊 

### ISSUE THREAD

**Issue by Jiangwentai** [JakeLaoyu/memos-import-from-flomo#18]
root@jiang-virtual-machine:/home/jiang/memos-import-from-flomo/memos-import-from-flomo# node ./src/main.js  

******ip*****
****token***
    /root/memos-import-from-flomo/flomo/index.html
/home/jiang/memos-import-from-flomo/memos-import-from-flomo/src/main.js:74
      memo.resourceIdList = res.map((item) => item.data?.id || item?.id);
                                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
root@jiang-virtual-machine:/home/jiang/memos-import-from-flomo/memos-import-from-flomo#

**Comment by JakeLaoyu** [comment]
发一份简单的测试数据，还有 memos 是什么版本

**Comment by Jiangwentai** [comment]
没有太接触过JS 似乎是版本的问题导致的?. 这个运算符出错
我自己重新写了个解析html 然后直接导入SQL的..
