### ISSUE TITLE
导入在上传了几个图片后报错

### ISSUE THREAD

**Issue by Chefback** [JakeLaoyu/memos-import-from-flomo#20]
版本使用的是0.18，最新版
备份时命令为：` node ./src/main.js http://ip/api/v1 token ./flomo/index.html`
代码唯一改动是sleep时间，改为5秒
flomo文件夹大小为37mb
以下为运行输出：
```
======================= 上传资源 =======================
开始上传 file/2023-12-27/80738/1703679343603B5690B6E73BF2723.jpg
开始上传 file/2023-12-27/80738/1703679343603B1DACB880D2CD113.jpg
开始上传 file/2023-12-27/80738/1703679343604B0CEB89D7A9F2FAE.jpg
开始上传 file/2023-12-27/80738/170367934360961AB8DB0F1593A4F.jpg
开始上传 file/2023-12-26/80738/1703593672100D28E0CCF6216A83A.jpg
开始上传 file/2023-12-22/80738/1703254062644982C43255AE5A492.jpg

/home/lin/memos-import-from-flomo/node_modules/.pnpm/axios@1.6.0/node_modules/axios/dist/node/axios.cjs:837
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError: read ECONNRESET
    at AxiosError.from (/home/lin/memos-import-from-flomo/node_modules/.pnpm/axios@1.6.0/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/home/lin/memos-import-from-flomo/node_modules/.pnpm/axios@1.6.0/node_modules/axios/dist/node/axios.cjs:3029:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/home/lin/memos-import-from-flomo/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -104,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: [Function: FormData] {
        LINE_BREAK: '\r\n',
        DEFAULT_CONTENT_TYPE: 'application/octet-stream'
      },
      Blob: [class Blob]
    },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data; boundary=--------------------------416973176555536863389662',
      Authorization: 'Bearer ',
      'User-Agent': 'axios/1.6.0',
      'Content-Length': '680712',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http:///api/v1/resource/blob',
    data: FormData {
      _overheadLength: 175,
      _valueLength: 680481,
      _valuesToMeasure: [],
      writable: false,
      readable: true,
      dataSize: 0,
      maxDataSize: 2097152,
      pauseStreams: true,
      _released: true,
      _streams: [],
      _currentStream: null,
      _insideLoop: false,
      _pendingNext: false,
      _boundary: '--------------------------416973176555536863389662',
      _events: [Object: null prototype] {
        end: [Function (anonymous)],
        error: [Function: bound onceWrapper] {
          listener: [Function (anonymous)]
        },
        close: [Function (anonymous)]
      },
      _eventsCount: 3
    }
  },
...
```

**Comment by JakeLaoyu** [comment]
`http://ip/api/v1` 看起来是这里解析失败了，方便发一下这个参数么

**Comment by ethanchengyu** [comment]
我看了下memos里面只有资源有导入图片，可是每一条memos文字都没有了，sleep改为5，其他也没改，能帮忙看一下吗

**Comment by JakeLaoyu** [comment]
@brmysss usememos 版本是多少

**Comment by ikuuto** [comment]
不太懂 JS，粗略看了下，可能是近期版本的 Memos API 的 V1 和 V2 有了很多不同，只有 V1 是使用 `/api/v1/resource/blob` 这样的 API，V2 变成了 `/api/v2/resources`，需要在 `api.js` 里锁定用 V1 而不是自动判断

**Comment by JakeLaoyu** [comment]
@ikuuto 感谢，最近有点忙，一直没时间看这个。我空闲的时候看一下这个问题

**Comment by JakeLaoyu** [comment]
@ikuuto @ethanchengyu @brmysss @Chefback  我试了一下没问题。应该是 sleep 时间太短了，触发了限流

<img width="731" alt="image" src="https://github.com/JakeLaoyu/memos-import-from-flomo/assets/16181940/083d849d-3d02-469f-8e19-6ffa5f19d840">
<img width="798" alt="image" src="https://github.com/JakeLaoyu/memos-import-from-flomo/assets/16181940/43d9ba94-8c72-45a6-8ec4-b2ef1882b0c5">
